// ================================================================
// Discord bridge
// ================================================================
// This bridge uses the Discord Gateway and REST API only for message transport.
// The model response is generated by the same local CLI-backed AssistantRuntime.

import { AccessStore } from "../core/access.ts";
import { chunkText } from "../utils/text.ts";
import { DEFAULT_FETCH_TIMEOUT_MS, fetchWithTimeout, type FetchLike } from "../utils/fetch.ts";
import { pairedMessage, pairingRequiredMessage } from "./telegram.ts";
import { connectorInputLimitMessage, connectorInputTooLong } from "./input-policy.ts";
import { ConnectorRateLimiter, connectorRateLimitMessage } from "./rate-limit.ts";
import type { AssistantRuntime } from "../core/assistant.ts";
import type { DiscordConnectorConfig } from "../core/types.ts";

const DISCORD_GATEWAY_URL = "wss://gateway.discord.gg/?v=10&encoding=json";
const DISCORD_API_BASE = "https://discord.com/api/v10";
const INTENTS = 1 | 512 | 4096 | 32768; // guilds, guild messages, DMs, message content

interface GatewayPayload {
  op: number;
  t?: string;
  s?: number;
  d?: any;
}

export interface DiscordMessage {
  id: string;
  channel_id: string;
  guild_id?: string;
  content: string;
  author: { id: string; bot?: boolean; username?: string };
}

export interface DiscordRequestOptions {
  fetchImpl?: FetchLike;
  timeoutMs?: number;
}

export async function runDiscordBridge(
  config: DiscordConnectorConfig,
  assistant: AssistantRuntime,
  access?: AccessStore
): Promise<void> {
  const token = config.botToken;
  if (!token) throw new Error(`Discord token is missing. Set ${config.botTokenEnv}.`);
  if (typeof WebSocket !== "function") throw new Error("This Node runtime does not provide WebSocket.");
  const rateLimiter = new ConnectorRateLimiter(config.maxMessagesPerMinute);

  let stopped = false;
  process.once("SIGINT", () => {
    stopped = true;
  });
  process.once("SIGTERM", () => {
    stopped = true;
  });

  console.log("Discord bridge is running. Press Ctrl+C to stop.");

  while (!stopped) {
    try {
      await connectDiscordGateway(token, config, assistant, () => stopped, access, rateLimiter);
    } catch (error) {
      if (stopped) break;
      console.error(error instanceof Error ? error.message : error);
      await new Promise((resolve) => setTimeout(resolve, 5000));
    }
  }
}

async function connectDiscordGateway(
  token: string,
  config: DiscordConnectorConfig,
  assistant: AssistantRuntime,
  shouldStop: () => boolean,
  access?: AccessStore,
  rateLimiter?: ConnectorRateLimiter
): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const socket = new WebSocket(DISCORD_GATEWAY_URL);
    let heartbeat: ReturnType<typeof setInterval> | undefined;
    let sequence: number | null = null;
    let botUserId: string | undefined;

    const send = (payload: unknown) => socket.send(JSON.stringify(payload));

    socket.addEventListener("open", () => {
      // Discord sends HELLO first; identify happens after we know heartbeat interval.
    });

    socket.addEventListener("message", (event) => {
      void (async () => {
        const packet = JSON.parse(String(event.data)) as GatewayPayload;
        if (typeof packet.s === "number") sequence = packet.s;

        if (packet.op === 10) {
          const interval = Number(packet.d.heartbeat_interval);
          heartbeat = setInterval(() => send({ op: 1, d: sequence }), interval);
          heartbeat.unref?.();
          send({
            op: 2,
            d: {
              token,
              intents: INTENTS,
              properties: { os: process.platform, browser: "viser", device: "viser" }
            }
          });
          return;
        }

        if (packet.op === 1) {
          send({ op: 1, d: sequence });
          return;
        }

        if (packet.t === "READY") {
          botUserId = packet.d.user.id;
          console.log(`Discord connected as ${packet.d.user.username}.`);
          return;
        }

        if (packet.t === "MESSAGE_CREATE") {
          await handleDiscordMessage(token, config, assistant, packet.d as DiscordMessage, botUserId, access, rateLimiter);
        }
      })().catch((error) => {
        if (heartbeat) clearInterval(heartbeat);
        reject(error instanceof Error ? error : new Error(String(error)));
        try {
          socket.close();
        } catch {
          // The promise rejection above is enough; close failures are ignored.
        }
      });
    });

    socket.addEventListener("error", () => reject(new Error("Discord gateway socket error.")));
    socket.addEventListener("close", () => {
      if (heartbeat) clearInterval(heartbeat);
      if (shouldStop()) resolve();
      else reject(new Error("Discord gateway closed; reconnecting."));
    });
  });
}

export async function handleDiscordMessage(
  token: string,
  config: DiscordConnectorConfig,
  assistant: AssistantRuntime,
  message: DiscordMessage,
  botUserId?: string,
  access?: AccessStore,
  rateLimiter?: ConnectorRateLimiter
): Promise<void> {
  if (!message.content || message.author.bot || message.author.id === botUserId) return;
  const staticAllowlist = [...config.allowedChannelIds, ...config.defaultChannelIds];
  if (config.allowedChannelIds.length > 0 && !staticAllowlist.includes(message.channel_id)) return;

  const normalized = normalizeDiscordInput(message.content, config.prefix, botUserId, Boolean(message.guild_id));
  if (!normalized) return;

  if (access && !(await access.isAllowed("discord", message.channel_id, staticAllowlist))) {
    const label = message.author.username ? `@${message.author.username}` : `discord:${message.channel_id}`;
    const paired = await access.tryPairCommand(normalized, "discord", message.channel_id, label);
    await sendDiscordMessage(token, message.channel_id, paired ? pairedMessage("discord") : pairingRequiredMessage("discord"));
    return;
  }

  if (connectorInputTooLong(normalized, config.maxInputChars)) {
    await sendDiscordMessage(token, message.channel_id, connectorInputLimitMessage(config.maxInputChars));
    return;
  }

  const rate = rateLimiter?.check(`discord:${message.channel_id}`);
  if (rate && !rate.allowed) {
    await sendDiscordMessage(token, message.channel_id, connectorRateLimitMessage(rate.retryAfterMs));
    return;
  }

  try {
    const answer = await assistant.handle(normalized, `discord:${message.channel_id}`, { source: "discord" });
    await sendDiscordMessage(token, message.channel_id, answer);
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    await sendDiscordMessage(token, message.channel_id, `Viser error:\n${detail}`);
  }
}

export function normalizeDiscordInput(content: string, prefix: string, botUserId: string | undefined, isGuild: boolean): string | undefined {
  const trimmed = content.trim();
  const mention = botUserId ? `<@${botUserId}>` : undefined;
  const nicknameMention = botUserId ? `<@!${botUserId}>` : undefined;

  if (!isGuild) return trimmed;
  if (trimmed.startsWith(prefix)) return trimmed.slice(prefix.length).trim() || "/help";
  if (mention && trimmed.startsWith(mention)) return trimmed.slice(mention.length).trim() || "/help";
  if (nicknameMention && trimmed.startsWith(nicknameMention)) return trimmed.slice(nicknameMention.length).trim() || "/help";
  return undefined;
}

export async function sendDiscordMessage(
  token: string,
  channelId: string,
  text: string,
  options: DiscordRequestOptions = {}
): Promise<void> {
  for (const chunk of chunkText(text, 1900)) {
    try {
      const response = await fetchWithTimeout(options.fetchImpl ?? fetch, `${DISCORD_API_BASE}/channels/${channelId}/messages`, {
        method: "POST",
        headers: {
          authorization: `Bot ${token}`,
          "content-type": "application/json"
        },
        body: JSON.stringify({ content: chunk })
      }, options.timeoutMs ?? DEFAULT_FETCH_TIMEOUT_MS);

      if (!response.ok) {
        const body = await response.text();
        throw new Error(`Discord send failed: ${response.status} ${body}`);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw new Error(redactToken(message, token));
    }
  }
}

function redactToken(detail: string, token: string): string {
  return detail.split(token).join("[REDACTED]");
}
